<template>
  <component :is="iconComponent" :size="size" :class="$attrs.class" />
</template>

<script>
import { defineComponent, computed } from 'vue';
import {
  CalendarDays,
  CalendarRange,
  Activity,
  Database,
  Search,
  Code,
  MoreHorizontal,
  Smartphone,
  Monitor,
  Settings,
  Wrench,
  Timer,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Plus,
  Minus,
  Trash2,
  Edit,
  Save,
  X,
  Eye,
  EyeOff,
  Copy,
  Download,
  Upload,
  RefreshCw,
  Check,
  AlertTriangle,
  Info,
  HelpCircle,
  Palette,
  Folder,
  File,
  List,
  BarChart2,
  Clock,
  Play,
  Pause,
  Square,
  ArrowUp,
  ArrowDown,
  Tag,
} from 'lucide-vue-next';

// Map FontAwesome icon names used across the codebase to Lucide equivalents
const iconMap = {
  'calendar-day': CalendarDays,
  'calendar-week': CalendarRange,
  'calendar': Calendar,
  'calendar-alt': Calendar,
  'stream': Activity,
  'database': Database,
  'search': Search,
  'code': Code,
  'ellipsis-h': MoreHorizontal,
  'mobile': Smartphone,
  'desktop': Monitor,
  'cog': Settings,
  'cogs': Settings,
  'tools': Wrench,
  'stopwatch': Timer,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ChevronLeft,
  'arrow-right': ChevronRight,
  'plus': Plus,
  'minus': Minus,
  'trash': Trash2,
  'trash-alt': Trash2,
  'edit': Edit,
  'pencil-alt': Edit,
  'save': Save,
  'times': X,
  'close': X,
  'eye': Eye,
  'eye-slash': EyeOff,
  'copy': Copy,
  'download': Download,
  'upload': Upload,
  'sync': RefreshCw,
  'sync-alt': RefreshCw,
  'check': Check,
  'exclamation-triangle': AlertTriangle,
  'info-circle': Info,
  'question-circle': HelpCircle,
  'palette': Palette,
  'folder': Folder,
  'file': File,
  'list': List,
  'chart-bar': BarChart2,
  'clock': Clock,
  'play': Play,
  'pause': Pause,
  'stop': Square,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'tag': Tag,
  'tags': Tag,
};

export default defineComponent({
  name: 'Icon',
  inheritAttrs: false,
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 16 },
  },
  computed: {
    iconComponent() {
      return iconMap[this.name] || HelpCircle;
    },
  },
});
</script>
